### ISSUE TITLE
details about the D module

### ISSUE THREAD

**Issue by wangqs97** [cszn/USRNet#1]
Hi cszn, thanks for this fantastic paper. I think the difference between this paper and DPSR is that H module and D module, but after reading I still don't know the details of D module.

Would you release the traing code in the future? If not, could you elaborate on the implementation of the D module? Thanks in advance.

**Comment by cszn** [comment]
DPSR and USRNet are essentially different methods.
- DPSR is a plug-and-play method which only needs to train on bicubic degradation.
- USRNet is a deep unfolding method which can be trained in an end-to-end manner.

I will release the code after the sponsor's approval.

The D module takes the noise level as input, you can refer to FFDNet as an example. It is not necessarily the same as ResUNet.

You may try to implement it by yourself.

**Comment by wangqs97** [comment]
Thanks, it's really helpful :)
