### ISSUE TITLE
How to get the deblur result?

### ISSUE THREAD

**Issue by honeytidy** [cszn/USRNet#10]
I run the demo `main_test_realapplication.py`  and can not get the deblur result like you provided example. My result is like this (seems deblur not work):
![image](https://user-images.githubusercontent.com/1021165/84889330-4b83cd00-b0cb-11ea-85d4-9c851c903b74.png)

**Comment by cszn** [comment]
Run [main_test_table1.py](https://github.com/cszn/USRNet/blob/master/main_test_table1.py) to get the results.

**Comment by anshulgarg11** [comment]
I ran the main_test_table1.py but getting similar blur output. I changed the scale factor to 1 before running. Please help. 

![](https://user-images.githubusercontent.com/1021165/84889330-4b83cd00-b0cb-11ea-85d4-9c851c903b74.png)

**Comment by ZurMaD** [comment]
Same issue here

**Comment by ZurMaD** [comment]
Complete Jupyter Notebook to run the model:
https://colab.research.google.com/drive/1erpZYSMxN0mAZEcgMmVbnhwoO3IdrTsh?usp=sharing
Results attached
[test.zip](https://github.com/cszn/USRNet/files/5076939/test.zip)

I think something it's happening with the model, looks like there're changes. However, they're not doing the work.

**Comment by cszn** [comment]
Read the paper first. You should set a proper kernel for the LR image.
