### ISSUE TITLE
Training codes ?

### ISSUE THREAD

**Issue by Darrenxc** [cszn/USRNet#11]
hi, 
this work looks amazing, do you have a plan to release the training codes? 
thank you

**Comment by cszn** [comment]
The training code will be included in [KAIR](https://github.com/cszn/KAIR).

**Comment by wanguangji2018** [comment]
Hello, 
this paper looks very novel. Can the training code of USRNetbe open source?  I can't find it KAIR.
Thank you very much

**Comment by wanguangji2018** [comment]
Hello,
this paper looks very novel. Can the training code of USRNetbe open source? I can't find it KAIR.
Thank you very much

**Comment by cszn** [comment]
I have already uploaded the [network design](https://github.com/cszn/KAIR/blob/6ac53385f707ca4c0e7242ce62ea123cea2a9d39/models/select_network.py#L148) and [dataset for dataloader](https://github.com/cszn/KAIR/blob/6ac53385f707ca4c0e7242ce62ea123cea2a9d39/data/select_dataset.py#L44), if you get familiar with KAIR, it is quite easy to make the training run.

_Originally posted by @cszn in https://github.com/cszn/KAIR/issues/27#issuecomment-665665521_

**Comment by litterbus** [comment]
ok, i got it ,thanks
