### ISSUE TITLE
Problems  during training

### ISSUE THREAD

**Issue by MakiseAsuka** [cszn/USRNet#13]
Hi, I am trying to write a training code based on the training code of DnCNN. I modified JSON file so that  "in_nc": 4 , "out_nc": 3       

But I still got an error saying that 

File "C:\Users\Daizo_\Documents\GitHub\KAIR\models\network_usrnet.py", line 357, in forward
    x = self.p(torch.cat((x, ab[:, i+self.n:i+self.n+1, ...].repeat(1, 1, x.size(2), x.size(3))), dim=1))
RuntimeError: Given groups=1, weight of size [64, 4, 3, 3], expected input[1, 2, 40, 40] to have 4 channels, but got 2 channels instead

If I change JSON to  "in_nc": 2 , "out_nc": 1 then there wont be this issue, but during testing I still get similar runtime error.

I am not sure how to train the model, could you please publish a training code that working?

Thanks a lot!

**Comment by cszn** [comment]
https://github.com/cszn/KAIR/blob/5d55a5fb88d20eb811dc7ccf6342b921039191cf/options/train_dncnn.json#L7
Set `n_channels` to 3 for color image and 1 for gray-scale image
