### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by ZahiLam** [cszn/USRNet#17]
@cszn Hi,This is a very interesting work!!👍 
Thank you so much for sharing your code ;)

At present, I can successfully run the training code by reference the code of  KAIR and test_usrnet and dpsr. 
But when I train, I only use one blur kernel and only considers scale factor 1.

I also use DIV2K800 as the training set, and set H_size to 48, batch_size to 32, and other parameters are basically the same as dpsr.

Currently I have run 400 epochs and the number of iterations is 10000,
But the test result at  BSD68  PSNR is only 22 ( scale factor is 1, use same blur kernel).

I want to consult could you provide more training details, such as the number of training iterations, whether to use 12 convolution kernels to join the training together, etc...

In addition, I would like to consult if you have tried not to use H_net to generate parameters, but to manually set them. If so, what range is better ?  (I am currently trying this approach)

Look forward to your reply :D

**Comment by cszn** [comment]
See https://github.com/cszn/KAIR/issues/31#issue-685180803

**Comment by ZahiLam** [comment]
Thank you very much for your reply,

I have two other questions

1. Regarding data loading, the number of kernels that generate L_img：

Is it to train 12 kernals together in different batches and finally train a network?
Or use 12 kernals to train 12 networks separately? (scale factor is the same problem)
(I read dataset_usrnet.py and cszn/KAIR#31 (comment)'s code on Kernel, but I don’t quite understand this.)

2. What is the approximate range of iterations(or epochs) to achieve better results?

**Comment by cszn** [comment]
1. The 12 kernels are not used for training but only for testing.
2. It depends on your GPU resource. At least 4  days with a single GPU.

**Comment by ZahiLam** [comment]
thank you :)

During the training process, the D_Net part needs to use the Kernel.
How to choose this part of the Kernel?

I am currently running with 8 2080Ti GPUs. After a day of running, G_loss has been in the range of around 5.194e-02. At what level did G_loss achieve better results when you running?

**Comment by cszn** [comment]
You should get the details from the training code.

**Comment by ZahiLam** [comment]
> should get the details from the training cod

I found the part of the code that defines the Kernel, 
thank you very much for answering me in your busy schedule, 

thank you very much!!
good9 :)

**Comment by sherlybe** [comment]
> @cszn Hi,This is a very interesting work!!👍
> Thank you so much for sharing your code ;)
> 
> At present, I can successfully run the training code by reference the code of KAIR and test_usrnet and dpsr.
> But when I train, I only use one blur kernel and only considers scale factor 1.
> 
> I also use DIV2K800 as the training set, and set H_size to 48, batch_size to 32, and other parameters are basically the same as dpsr.
> 
> Currently I have run 400 epochs and the number of iterations is 10000,
> But the test result at BSD68 PSNR is only 22 ( scale factor is 1, use same blur kernel).
> 
> I want to consult could you provide more training details, such as the number of training iterations, whether to use 12 convolution kernels to join the training together, etc...
> 
> In addition, I would like to consult if you have tried not to use H_net to generate parameters, but to manually set them. If so, what range is better ? (I am currently trying this approach)
> 
> Look forward to your reply :D

[我还是用中文跟您交流吧。我也在做跟您一样的事情，](https://github.com/cszn/KAIR/issues/69)您可以看一下这个连接的问题，您有什么建议？

- [ ]
