### ISSUE TITLE
main_test_table1.py

### ISSUE THREAD

**Issue by peoplecure** [cszn/USRNet#19]
Hi, when I run ``main_test_table1.py``, I get following error: ``FileNotFoundError: [Errno 2] No such file or directory: 'model_zoo/usrnet.pth'``

So, I looked inside ``model_zoo`` folder, but I could not find usrnet.pth.

**Comment by sherlybe** [comment]
Hi,I have the same question.
how to solve it?
thank u

**Comment by cszn** [comment]
Download the trained model first, see https://github.com/cszn/USRNet/tree/master/model_zoo
