### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'rfft'

### ISSUE THREAD

**Issue by Lingcan-M** [cszn/USRNet#23]
I got this error while run main_test_realapplication.py program. The running environment is pytorch 1.8.
May I ask how to deal with this problem?

**Comment by cszn** [comment]
Use pytorch version <=1.7.1 and I will update my code in this week.

**Comment by Lingcan-M** [comment]
Thank you.

**Comment by cszn** [comment]
I upload the code to support pytorch version >= 1.8.1
https://github.com/cszn/USRNet/blob/17d80ebd4e8f34ac76612fd660412bf616baf84d/models/network_usrnet_v1.py
