### ISSUE TITLE
onesided parameter is supported in torch 1.8.1

### ISSUE THREAD

**Issue by thesby** [cszn/USRNet#24]
`otf = torch.rfft(otf, 2, onesided=False)` is compatible with torch 1.8.1

**Comment by peylnog** [comment]
I met the same question.  
otf = torch.rfft(otf, 2, onesided=False) is incompatible with torch 1.8.1

**Comment by cszn** [comment]
https://github.com/cszn/USRNet/blob/6f04b69564e7a074615d82b5e9878efba649e710/main_test_table1.py#L22
