### ISSUE TITLE
blur_kernel

### ISSUE THREAD

**Issue by xiexiaozheng** [cszn/USRNet#5]
@cszn 你好，我问一下论文代码里的模糊核是已知项还是未知项，看你论文里写的是已知模糊核输入，然后去模糊，这里有点不明白

**Comment by cszn** [comment]
This work focuses on non-blind SISR which assumes the blur kernel and noise level are known beforehand. In fact, non-blind SISR is still an active research direction.

- First, the blur kernel and noise level can be estimated, or are known based on other information (e.g., camera setting).
- Second, users can control the preference of sharpness and smoothness by tuning the blur kernel and noise level.
- Third, non-blind SISR can be an intermediate step towards solving blind SISR.
